double		pow(double x, double y)
{
    double	r = x;

    if (y <= 0)
        return (1.0);
    if (y == 1)
        return (x);

    while (y > 1)
    {
        r *= x;
        y--;
    }

    return (r);
}

double	fabs(double x)
{
    return (x < 0 ? -x : x);
}

/*
    The implementations of sin, cos, tan and exp here
    were generated by LolRemez, http://lolengine.net/wiki/oss/lolremez

    TODO: use better implementations(like glibc or something like that)
*/

double sin(double x)
{
    static const
    double a0 =  1.0,
           a1 = -1.666666666640169148537065260055e-1,
           a2 =  8.333333316490113523036717102793e-3,
           a3 = -1.984126600659171392655484413285e-4,
           a4 =  2.755690114917374804474016589137e-6,
           a5 = -2.502845227292692953118686710787e-8,
           a6 =  1.538730635926417598443354215485e-10;
    double x2 = x * x;
    return x * (a0 + x2 * (a1 + x2 * (a2 + x2
             * (a3 + x2 * (a4 + x2 * (a5 + x2 * a6))))));
}

double cos(double x)
{
    const double a0 = 9.99959174689540053e-1;
    const double a1 = 1.35263438100583208e-5;
    const double a2 = -4.99238704253639242e-1;
    const double a3 = -5.43517523575486391e-5;
    const double a4 = 3.95818354322389060e-2;

    return a0 + x * (a1 + x * (a2 + x * (a3 + x * a4)));
}

double tan(double x)
{
    const double a0 = 1.02552185054002842e-153;
    const double a1 = 9.08426171426218458e-1;
    const double a2 = -6.11583939958416952e-153;
    const double a3 = 6.28822891947394513e-1;
    const double a4 = 4.32583762409611991e-153;

    return a0 + x * (a1 + x * (a2 + x * (a3 + x * a4)));
}

double exp(double x)
{
    const double a0 = 4.221396646731853477890919644216017231587;
    const double a1 = -2.615291204757967766624186359891455241753;
    const double a2 = -1.032749880400710397703832804115474876830;
    const double a3 = 6.586172186945825481523412117510136175816e-1;
    const double a4 = 1.532916782209180014540976136050537099408e-1;

    return a0 + x * (a1 + x * (a2 + x * (a3 + x * a4)));
}
