CUR_DIR		:= core/kernel/

OBJS		:=	cmdline.o	\
			cpuinfo.o	\
			cpuid_check.o 	\
			kbd.o		\
			irq.o 		\
			isr.o		\
			panic.o		\
			printk.o	\
			pit.o		\
			traps.o		\
			traps_support.o \
			tty.o		\
			serial.o	\
			vsprintf.o	\
			console.o	\
			video.o		\
			reboot.o

PROGSUBDIRS	:=

include $Omk/progsubdirs.mk
