CUR_DIR		:= core/kernel/

OBJS		:=	irq.o 		\
			isr.o		\
			panic.o		\
			printk.o	\
			sys_call.o	\
			traps.o		\
			tty.o		\
			serial.o	\
			vfs_open.o	\
			vsprintf.o

PROGSUBDIRS	:=

include $Omk/progsubdirs.mk
